// <auto-generated />
using CampusDeal.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusDeal.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230621063926_foreignKeySeed")]
    partial class foreignKeySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusDeal.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Goods"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Services"
                        });
                });

            modelBuilder.Entity("CampusDeal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PriceTotal")
                        .HasColumnType("float");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "the maths book",
                            PNO = "A01",
                            Price = 400.0,
                            PriceTotal = 400.0,
                            Seller = "john wick",
                            Title = "Book"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "the maths notebook",
                            PNO = "A02",
                            Price = 200.0,
                            PriceTotal = 200.0,
                            Seller = "john snow",
                            Title = "notebook"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "the kit for science lab",
                            PNO = "A03",
                            Price = 150.0,
                            PriceTotal = 150.0,
                            Seller = "john cena",
                            Title = " Science lab kit"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "laptop in a very good condition. acer aspire 5 250GB ssd, 1 tb HDD, intel5 7gen 4 GB graphics  ",
                            PNO = "A04",
                            Price = 40000.0,
                            PriceTotal = 39000.0,
                            Seller = "billie",
                            Title = "Laptop"
                        });
                });

            modelBuilder.Entity("CampusDeal.Models.Product", b =>
                {
                    b.HasOne("CampusDeal.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
